name := "SupervisedMLRF"
version := "1.0"
scalaVersion := "2.12.15"
libraryDependencies += "org.apache.spark" %% "spark-core" % "3.3.0"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "3.3.0"
libraryDependencies += "org.scala-lang" % "scala-library" % "2.12.17"
libraryDependencies += "org.scala-lang" % "scala-compiler" % "2.12.17"
libraryDependencies += "org.scala-lang" % "scala-reflect" % "2.12.17"
